# ARG NODE_VERSION=20
# ARG DEBIAN_FRONTEND=noninteractive

# FROM node:${NODE_VERSION} as flowers-api-base

# WORKDIR /api

# COPY package.json package.json
# COPY package-lock.json package-lock.json

# # -- DEV
# FROM flowers-api-base as flowers-api-dev

# ENTRYPOINT [ "./init.sh" ]